name: Docker Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ['1.31', '1.35', '1.36', '1.37']
        type: [apache, fpm, fpm-alpine]

    steps:
    - uses: actions/checkout@v1
    - run: docker build ./${{ matrix.version }}/${{ matrix.type }}
